"""Initial migration

Revision ID: 6d5c800f165c
Revises: 
Create Date: 2025-02-19 21:58:48.677945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d5c800f165c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Stock')
    op.drop_table('PortfolioStock')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('price')
        batch_op.drop_column('name')

    with op.batch_alter_table('new_Data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('Metrics', schema=None) as batch_op:
        batch_op.alter_column('metric',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('Metric_ID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)

    with op.batch_alter_table('Companies', schema=None) as batch_op:
        batch_op.alter_column('company',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('Company_ID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)

    op.create_table('stock_prices',
    sa.Column('date', sa.TEXT(), nullable=True),
    sa.Column('open', sa.REAL(), nullable=True),
    sa.Column('high', sa.REAL(), nullable=True),
    sa.Column('low', sa.REAL(), nullable=True),
    sa.Column('close', sa.REAL(), nullable=True),
    sa.Column('volume', sa.INTEGER(), nullable=True),
    sa.Column('dividend', sa.REAL(), nullable=True),
    sa.Column('StockSplits', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('Data',
    sa.Column('Date', sa.TIMESTAMP(), nullable=True),
    sa.Column('Company_ID', sa.INTEGER(), nullable=True),
    sa.Column('Metric_ID', sa.INTEGER(), nullable=True),
    sa.Column('value', sa.REAL(), nullable=True)
    )
    op.create_table('Products',
    sa.Column('Product_ID', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('Product_ID')
    )
    # ### end Alembic commands ###
