"""empty message

Revision ID: 97049416f3a8
Revises: 6d5c800f165c
Create Date: 2025-02-25 16:46:54.113304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97049416f3a8'
down_revision = '6d5c800f165c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Stock')
    op.drop_table('Portfolio_Stock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'stock', ['stock_id'], ['id'])
        batch_op.drop_column('company_id')

    with op.batch_alter_table('new_Data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('Metrics', schema=None) as batch_op:
        batch_op.alter_column('metric',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('Metric_ID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)

    with op.batch_alter_table('Companies', schema=None) as batch_op:
        batch_op.alter_column('company',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('Company_ID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)

    op.create_table('Data',
    sa.Column('Date', sa.TIMESTAMP(), nullable=True),
    sa.Column('Company_ID', sa.INTEGER(), nullable=True),
    sa.Column('Metric_ID', sa.INTEGER(), nullable=True),
    sa.Column('value', sa.REAL(), nullable=True)
    )
    op.create_table('stock_prices',
    sa.Column('date', sa.TEXT(), nullable=True),
    sa.Column('open', sa.REAL(), nullable=True),
    sa.Column('high', sa.REAL(), nullable=True),
    sa.Column('low', sa.REAL(), nullable=True),
    sa.Column('close', sa.REAL(), nullable=True),
    sa.Column('volume', sa.INTEGER(), nullable=True),
    sa.Column('dividend', sa.REAL(), nullable=True),
    sa.Column('StockSplits', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###
